spring:
  datasource:
    url: jdbc:mysql://localhost:${env.DB_PORT}/${env.DB_NAME}?createDatabaseIfNotExist=true&userSSL=true&useUnicode=true&allowPublicKeyRetrieval=true&useSSL=false
    username: ${env.DB_USER}
    password: ${env.DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    database: mysql
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
server:
  port: ${env.APP_PORT}
jwt:
  secret: ${env.JWT_SECRET_KEY}
